"""empty message

Revision ID: 08efae493dee
Revises: 2cb68c352edc
Create Date: 2025-10-16 23:24:09.529734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08efae493dee"
down_revision: Union[str, Sequence[str], None] = "2cb68c352edc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tariff_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "tariff_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
