"""empty message

Revision ID: 1f909823799e
Revises: 3af1088677eb
Create Date: 2025-10-16 15:39:59.831783

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f909823799e"
down_revision: Union[str, Sequence[str], None] = "3af1088677eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.VARCHAR(length=12),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=12),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
