"""empty message

Revision ID: 2cb68c352edc
Revises: e0a5d9e66d61
Create Date: 2025-10-16 23:22:43.698631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cb68c352edc"
down_revision: Union[str, Sequence[str], None] = "e0a5d9e66d61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tariff_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "users", "tariffs", ["tariff_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "tariff_id")
    # ### end Alembic commands ###
