"""empty message

Revision ID: 3dbb1a34bf9b
Revises: 1f909823799e
Create Date: 2025-10-16 22:20:23.725844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3dbb1a34bf9b"
down_revision: Union[str, Sequence[str], None] = "1f909823799e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chalenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("prize", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "challenge_user_association_table",
        sa.Column("left_id", sa.Integer(), nullable=False),
        sa.Column("right_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["chalenges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("left_id", "right_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("challenge_user_association_table")
    op.drop_table("chalenges")
    # ### end Alembic commands ###
