"""empty message

Revision ID: 699297c28514
Revises: 08efae493dee
Create Date: 2025-10-16 23:26:08.117968

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "699297c28514"
down_revision: Union[str, Sequence[str], None] = "08efae493dee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tariff_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("tariff_status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
